addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.1.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.12")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"                  % "1.2.0")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                       % "2.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "3.9.11")
//addSbtPlugin("com.orrsella"       % "sbt-stats"                     % "1.0.7")