package com.github.mzdb4s.io.thermo.bindings

import scala.language.implicitConversions
import scala.scalanative.unsafe._
import scala.scalanative.unsigned._

@link("ThermoRawFileParser")
@extern
object ThermoRawFileParser {

  type enum_ThermoRawFileParser_OutputFormat = CUnsignedInt
  object enum_ThermoRawFileParser_OutputFormat {
    final val ThermoRawFileParser_OutputFormat_MGF: enum_ThermoRawFileParser_OutputFormat = 0.toUInt
    final val ThermoRawFileParser_OutputFormat_MzML: enum_ThermoRawFileParser_OutputFormat = 1.toUInt
    final val ThermoRawFileParser_OutputFormat_IndexMzML: enum_ThermoRawFileParser_OutputFormat = 2.toUInt
    final val ThermoRawFileParser_OutputFormat_Parquet: enum_ThermoRawFileParser_OutputFormat = 3.toUInt
    final val ThermoRawFileParser_OutputFormat_NONE: enum_ThermoRawFileParser_OutputFormat = 4.toUInt
  }

  type enum_ThermoRawFileParser_MetadataFormat = CUnsignedInt
  object enum_ThermoRawFileParser_MetadataFormat {
    final val ThermoRawFileParser_MetadataFormat_JSON: enum_ThermoRawFileParser_MetadataFormat = 0.toUInt
    final val ThermoRawFileParser_MetadataFormat_TXT: enum_ThermoRawFileParser_MetadataFormat = 1.toUInt
    final val ThermoRawFileParser_MetadataFormat_PARQUET: enum_ThermoRawFileParser_MetadataFormat = 2.toUInt
    final val ThermoRawFileParser_MetadataFormat_NONE: enum_ThermoRawFileParser_MetadataFormat = 3.toUInt
  }

  type enum_ThermoRawFileParser_LogFormat = CUnsignedInt
  object enum_ThermoRawFileParser_LogFormat {
    final val ThermoRawFileParser_LogFormat_SILENT: enum_ThermoRawFileParser_LogFormat = 0.toUInt
    final val ThermoRawFileParser_LogFormat_VERBOSE: enum_ThermoRawFileParser_LogFormat = 1.toUInt
    final val ThermoRawFileParser_LogFormat_DEFAULT: enum_ThermoRawFileParser_LogFormat = 2.toUInt
    final val ThermoRawFileParser_LogFormat_NONE: enum_ThermoRawFileParser_LogFormat = 3.toUInt
  }

  type enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = CUnsignedInt
  object enum_ThermoRawFileParser_Writer_MzML_IndexTypeName {
    final val ThermoRawFileParser_Writer_MzML_IndexTypeName_spectrum: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = 0.toUInt
    final val ThermoRawFileParser_Writer_MzML_IndexTypeName_chromatogram: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = 1.toUInt
  }

  type __int32_t = CInt
  type __uint32_t = CUnsignedInt
  type __int64_t = CLong
  type int32_t = __int32_t
  type int64_t = __int64_t
  type uint32_t = __uint32_t
  type gint = CInt
  type struct__GArray = CStruct2[CString, gint]
  type GArray = struct__GArray
  type struct_MonoEmbedObject = CStruct2[Ptr[MonoClass], uint32_t]
  type MonoEmbedObject = struct_MonoEmbedObject
  type struct__MonoClass = CStruct0 // incomplete type
  type MonoClass = struct__MonoClass
  type struct_MonoEmbedArray = CStruct1[Ptr[GArray]]
  type MonoEmbedArray = struct_MonoEmbedArray
  type _ByteArray = MonoEmbedArray
  type _DoubleArray = MonoEmbedArray
  type _StringArray = MonoEmbedArray
  type ThermoRawFileParser_OutputFormat = enum_ThermoRawFileParser_OutputFormat
  type ThermoRawFileParser_MetadataFormat = enum_ThermoRawFileParser_MetadataFormat
  type ThermoRawFileParser_LogFormat = enum_ThermoRawFileParser_LogFormat
  type ThermoRawFileParser_Writer_MzML_IndexTypeName = enum_ThermoRawFileParser_Writer_MzML_IndexTypeName
  type _ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_CVParamTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_UserParamTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ParamGroupTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ScanTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_PrecursorTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ProductTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_BinaryDataArrayTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_CVTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceFileTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SampleTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SoftwareTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceFileRefTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ScanSettingsTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SourceComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_AnalyzerComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_DetectorComponentTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_InstrumentConfigurationTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ProcessingMethodTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_DataProcessingTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_SpectrumTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_ChromatogramTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_OffsetTypeArray = MonoEmbedArray
  type _ThermoRawFileParser_Writer_MzML_IndexTypeArray = MonoEmbedArray
  type ThermoRawFileParser_RawFileWrapper = MonoEmbedObject
  type ThermoRawFileParser_ParseInput = MonoEmbedObject
  type ThermoRawFileParser_Writer_S3Loader = MonoEmbedObject
  type ThermoRawFileParser_MainClass = MonoEmbedObject
  type ThermoRawFileParser_RawFileParserException = MonoEmbedObject
  type ThermoRawFileParser_RawFileParser = MonoEmbedObject
  type ThermoRawFileParser_Writer_SpectrumWrapper = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SpectrumType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ParamGroupType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVParamType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_UserParamType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanWindowListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_PrecursorListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_PrecursorType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SelectedIonListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProductListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProductType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_BinaryDataArrayType = MonoEmbedObject
  type ThermoRawFileParser_Writer_ISpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_Metadata = MonoEmbedObject
  type ThermoRawFileParser_Writer_CVTerm = MonoEmbedObject
  type ThermoRawFileParser_Writer_ProxiCvTerm = MonoEmbedObject
  type ThermoRawFileParser_Writer_MetadataWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_MgfSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_SpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzMlSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_OntologyMapping = MonoEmbedObject
  type ThermoRawFileParser_Writer_ParquetSpectrumWriter = MonoEmbedObject
  type ThermoRawFileParser_Writer_PScan = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_mzMLType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_CVType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_FileDescriptionType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SampleListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SampleType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanSettingsListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ScanSettingsType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileRefListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceFileRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_TargetListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ComponentListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SourceComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_AnalyzerComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DetectorComponentType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SoftwareRefType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DataProcessingListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_DataProcessingType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ProcessingMethodType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_RunType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_SpectrumListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ChromatogramListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_ChromatogramType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_OffsetType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_IndexType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_IndexListType = MonoEmbedObject
  type ThermoRawFileParser_Writer_MzML_indexedmzML = MonoEmbedObject
  type ThermoRawFileParser_XIC_JSONInputUnit = MonoEmbedObject
  type ThermoRawFileParser_XIC_JSONParser = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicData = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicOutputMeta = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicExecutor = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicParameters = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicMeta = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicReader = MonoEmbedObject
  type ThermoRawFileParser_XIC_XicUnit = MonoEmbedObject
  type ThermoRawFileParser_Util_LimitedSizeDictionary_2 = MonoEmbedObject
  type ThermoRawFileParser_Util_TKey = MonoEmbedObject
  type ThermoRawFileParser_Util_TValue = MonoEmbedObject
  type ThermoRawFileParser_Util_PeptideData = MonoEmbedObject
  type ThermoRawFileParser_Util_Peptide = MonoEmbedObject
  type ThermoRawFileParser_Query_ProxiSpectrum = MonoEmbedObject
  type ThermoRawFileParser_Query_QueryParameters = MonoEmbedObject
  type ThermoRawFileParser_Query_QueryExecutor = MonoEmbedObject
  type ThermoRawFileParser_Query_ProxiSpectrumReader = MonoEmbedObject
  def ThermoRawFileParser_RawFileWrapper_Dispose(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper]): Unit = extern
  def ThermoRawFileParser_RawFileWrapper_get_FirstScanNumber(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper]): int32_t = extern
  def ThermoRawFileParser_RawFileWrapper_set_FirstScanNumber(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper], value: int32_t): Unit = extern
  def ThermoRawFileParser_RawFileWrapper_get_LastScanNumber(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper]): int32_t = extern
  def ThermoRawFileParser_RawFileWrapper_set_LastScanNumber(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper], value: int32_t): Unit = extern
  def ThermoRawFileParser_RawFileWrapper_get_ParseInput(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper]): Ptr[ThermoRawFileParser_ParseInput] = extern
  def ThermoRawFileParser_RawFileWrapper_set_ParseInput(objectPtr: Ptr[ThermoRawFileParser_RawFileWrapper], value: Ptr[ThermoRawFileParser_ParseInput]): Unit = extern
  def ThermoRawFileParser_ParseInput_new(): Ptr[ThermoRawFileParser_ParseInput] = extern
  def ThermoRawFileParser_ParseInput_new_1(rawFilePath: CString, rawDirectoryPath: CString, outputDirectory: CString, outputFormat: enum_ThermoRawFileParser_OutputFormat): Ptr[ThermoRawFileParser_ParseInput] = extern
  def ThermoRawFileParser_ParseInput_InitializeS3Bucket(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): Unit = extern
  def ThermoRawFileParser_ParseInput_get_RawDirectoryPath(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_RawDirectoryPath(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_RawFilePath(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_RawFilePath(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_UseInMemoryWriter(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CBool = extern
  def ThermoRawFileParser_ParseInput_set_UseInMemoryWriter(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CBool): Unit = extern
  def ThermoRawFileParser_ParseInput_get_OutputDirectory(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_OutputDirectory(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_OutputFile(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_OutputFile(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_OutputFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_OutputFormat = extern
  def ThermoRawFileParser_ParseInput_set_OutputFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_OutputFormat): Unit = extern
  def ThermoRawFileParser_ParseInput_get_MetadataFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_MetadataFormat = extern
  def ThermoRawFileParser_ParseInput_set_MetadataFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_MetadataFormat): Unit = extern
  def ThermoRawFileParser_ParseInput_get_MetadataOutputFile(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_MetadataOutputFile(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_Gzip(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CBool = extern
  def ThermoRawFileParser_ParseInput_set_Gzip(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CBool): Unit = extern
  def ThermoRawFileParser_ParseInput_get_NoPeakPicking(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CBool = extern
  def ThermoRawFileParser_ParseInput_set_NoPeakPicking(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CBool): Unit = extern
  def ThermoRawFileParser_ParseInput_get_NoZlibCompression(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CBool = extern
  def ThermoRawFileParser_ParseInput_set_NoZlibCompression(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CBool): Unit = extern
  def ThermoRawFileParser_ParseInput_get_LogFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): enum_ThermoRawFileParser_LogFormat = extern
  def ThermoRawFileParser_ParseInput_set_LogFormat(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: enum_ThermoRawFileParser_LogFormat): Unit = extern
  def ThermoRawFileParser_ParseInput_get_IgnoreInstrumentErrors(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CBool = extern
  def ThermoRawFileParser_ParseInput_set_IgnoreInstrumentErrors(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CBool): Unit = extern
  def ThermoRawFileParser_ParseInput_get_S3Loader(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): Ptr[ThermoRawFileParser_Writer_S3Loader] = extern
  def ThermoRawFileParser_ParseInput_set_S3Loader(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: Ptr[ThermoRawFileParser_Writer_S3Loader]): Unit = extern
  def ThermoRawFileParser_ParseInput_get_S3AccessKeyId(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_S3AccessKeyId(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_S3SecretAccessKey(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_S3SecretAccessKey(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_S3Url(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_S3Url(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_BucketName(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_BucketName(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_ParseInput_get_RawFileNameWithoutExtension(objectPtr: Ptr[ThermoRawFileParser_ParseInput]): CString = extern
  def ThermoRawFileParser_ParseInput_set_RawFileNameWithoutExtension(objectPtr: Ptr[ThermoRawFileParser_ParseInput], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_S3Loader_new(s3url: CString, s3AccessKeyId: CString, s3SecretAccessKey: CString, bucketName: CString): Ptr[ThermoRawFileParser_Writer_S3Loader] = extern
  def ThermoRawFileParser_Writer_S3Loader_loadObjectToS3(objectPtr: Ptr[ThermoRawFileParser_Writer_S3Loader], filePath: CString, name: CString, contentType: CString, label: CString): CBool = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_getPeaksCount(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper]): int32_t = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_GetMzValue(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], pos: int32_t): CDouble = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_GetIntensityValue(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], pos: int32_t): CDouble = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyMzListToPointer(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], ptrAddress: int64_t): Unit = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyIntensityListToPointer(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], ptrAddress: int64_t): Unit = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_CopyDataToPointers(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], mzPtrAddress: int64_t, intensityPtrAddress: int64_t): Unit = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_get_Spectrum(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper]): Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType] = extern
  def ThermoRawFileParser_Writer_SpectrumWrapper_set_Spectrum(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWrapper], value: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_scanList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Ptr[ThermoRawFileParser_Writer_MzML_ScanListType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_scanList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: Ptr[ThermoRawFileParser_Writer_MzML_ScanListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_precursorList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_precursorList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_productList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Ptr[ThermoRawFileParser_Writer_MzML_ProductListType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_productList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: Ptr[ThermoRawFileParser_Writer_MzML_ProductListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_binaryDataArrayList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_binaryDataArrayList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_spotID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_spotID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_index(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_index(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_defaultArrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): int32_t = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_defaultArrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_get_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumType_set_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ScanListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ScanType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_scanWindowList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_scanWindowList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_spectrumRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_spectrumRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_externalSpectrumID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_externalSpectrumID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_get_instrumentConfigurationRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanType_set_instrumentConfigurationRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType]): int32_t = extern
  def ThermoRawFileParser_Writer_MzML_ScanWindowListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanWindowListType], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ParamGroupType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType] = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_get_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType_set_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupRefType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_new(): Ptr[ThermoRawFileParser_Writer_MzML_CVParamType] = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_cvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_cvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_accession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_accession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_get_unitCvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVParamType_set_unitCvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_new(): Ptr[ThermoRawFileParser_Writer_MzML_UserParamType] = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_type(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_type(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_get_unitCvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_UserParamType_set_unitCvRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_UserParamType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType] = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_new(): Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType] = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_isolationWindow(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_isolationWindow(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_selectedIonList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType] = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_selectedIonList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_activation(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_activation(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_spectrumRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_spectrumRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_sourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_get_externalSpectrumID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_PrecursorType_set_externalSpectrumID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType] = extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SelectedIonListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SelectedIonListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ProductListType] = extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProductListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ProductListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProductListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ProductType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ProductType] = extern
  def ThermoRawFileParser_Writer_MzML_ProductType_get_isolationWindow(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProductType]): Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_ProductType_set_isolationWindow(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProductType], value: Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_new(): Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType] = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_arrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_arrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_get_encodedLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_BinaryDataArrayType_set_encodedLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_new(): Ptr[ThermoRawFileParser_Writer_MzML_mzMLType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_cvList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_CVListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_cvList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_CVListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_fileDescription(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_fileDescription(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_referenceableParamGroupList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_referenceableParamGroupList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_sampleList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_SampleListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_sampleList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_SampleListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_softwareList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_softwareList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_scanSettingsList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_scanSettingsList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_instrumentConfigurationList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_instrumentConfigurationList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_dataProcessingList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_dataProcessingList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_run(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Ptr[ThermoRawFileParser_Writer_MzML_RunType] = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_run(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_accession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_accession(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_mzMLType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_CVListType] = extern
  def ThermoRawFileParser_Writer_MzML_CVListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVType_new(): Ptr[ThermoRawFileParser_Writer_MzML_CVType] = extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_fullName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_fullName(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_CVType_get_URI(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_CVType_set_URI(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_CVType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_new(): Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType] = extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_get_fileContent(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_set_fileContent(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType], value: Ptr[ThermoRawFileParser_Writer_MzML_ParamGroupType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_get_sourceFileList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType]): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType] = extern
  def ThermoRawFileParser_Writer_MzML_FileDescriptionType_set_sourceFileList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_FileDescriptionType], value: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType] = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType] = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_get_location(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileType_set_location(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType] = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType] = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ReferenceableParamGroupType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SampleListType] = extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SampleListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SampleType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SampleType] = extern
  def ThermoRawFileParser_Writer_MzML_SampleType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SampleType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SampleType_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SampleType_set_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SampleType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType] = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType] = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_get_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareType_set_version(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_sourceFileRefList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_sourceFileRefList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_targetList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): Ptr[ThermoRawFileParser_Writer_MzML_TargetListType] = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_targetList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: Ptr[ThermoRawFileParser_Writer_MzML_TargetListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ScanSettingsType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ScanSettingsType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType] = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType] = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_get_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SourceFileRefType_set_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SourceFileRefType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_TargetListType] = extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_TargetListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_TargetListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_TargetListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType] = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_new(): Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType] = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_componentList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType] = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_componentList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_softwareRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType] = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_softwareRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_get_scanSettingsRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType_set_scanSettingsRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_InstrumentConfigurationType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType] = extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ComponentListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ComponentListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SourceComponentType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SourceComponentType] = extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ComponentType] = extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_get_order(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ComponentType]): int32_t = extern
  def ThermoRawFileParser_Writer_MzML_ComponentType_set_order(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ComponentType], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzML_AnalyzerComponentType_new(): Ptr[ThermoRawFileParser_Writer_MzML_AnalyzerComponentType] = extern
  def ThermoRawFileParser_Writer_MzML_DetectorComponentType_new(): Ptr[ThermoRawFileParser_Writer_MzML_DetectorComponentType] = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType] = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_get_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SoftwareRefType_set_ref(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SoftwareRefType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType] = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_new(): Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType] = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_DataProcessingType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_DataProcessingType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType] = extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_get_order(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_set_order(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_get_softwareRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ProcessingMethodType_set_softwareRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ProcessingMethodType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_new(): Ptr[ThermoRawFileParser_Writer_MzML_RunType] = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_spectrumList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType] = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_spectrumList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_chromatogramList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType] = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_chromatogramList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_defaultInstrumentConfigurationRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_defaultInstrumentConfigurationRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_defaultSourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_defaultSourceFileRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_sampleRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_sampleRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_RunType_get_startTimeStampSpecified(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType]): CBool = extern
  def ThermoRawFileParser_Writer_MzML_RunType_set_startTimeStampSpecified(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_RunType], value: CBool): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType] = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_get_defaultDataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_SpectrumListType_set_defaultDataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_SpectrumListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType] = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_get_defaultDataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramListType_set_defaultDataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_new(): Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType] = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_precursor(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType] = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_precursor(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: Ptr[ThermoRawFileParser_Writer_MzML_PrecursorType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_product(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): Ptr[ThermoRawFileParser_Writer_MzML_ProductType] = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_product(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: Ptr[ThermoRawFileParser_Writer_MzML_ProductType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_binaryDataArrayList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType] = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_binaryDataArrayList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: Ptr[ThermoRawFileParser_Writer_MzML_BinaryDataArrayListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_id(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_index(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_index(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_defaultArrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): int32_t = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_defaultArrayLength(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_get_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_ChromatogramType_set_dataProcessingRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_ChromatogramType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_new(): Ptr[ThermoRawFileParser_Writer_MzML_OffsetType] = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_idRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_idRef(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_spotID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_spotID(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTime(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): CDouble = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTime(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_scanTimeSpecified(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): CBool = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_scanTimeSpecified(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: CBool): Unit = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_get_Value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType]): int64_t = extern
  def ThermoRawFileParser_Writer_MzML_OffsetType_set_Value(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_OffsetType], value: int64_t): Unit = extern
  def ThermoRawFileParser_Writer_MzML_IndexType_new(): Ptr[ThermoRawFileParser_Writer_MzML_IndexType] = extern
  def ThermoRawFileParser_Writer_MzML_IndexType_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_IndexType]): enum_ThermoRawFileParser_Writer_MzML_IndexTypeName = extern
  def ThermoRawFileParser_Writer_MzML_IndexType_set_name(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_IndexType], value: enum_ThermoRawFileParser_Writer_MzML_IndexTypeName): Unit = extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_new(): Ptr[ThermoRawFileParser_Writer_MzML_IndexListType] = extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_get_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_IndexListType]): CString = extern
  def ThermoRawFileParser_Writer_MzML_IndexListType_set_count(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_IndexListType], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_new(): Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML] = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_mzML(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): Ptr[ThermoRawFileParser_Writer_MzML_mzMLType] = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_mzML(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: Ptr[ThermoRawFileParser_Writer_MzML_mzMLType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_indexList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): Ptr[ThermoRawFileParser_Writer_MzML_IndexListType] = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_indexList(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: Ptr[ThermoRawFileParser_Writer_MzML_IndexListType]): Unit = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_get_fileChecksum(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML]): CString = extern
  def ThermoRawFileParser_Writer_MzML_indexedmzML_set_fileChecksum(objectPtr: Ptr[ThermoRawFileParser_Writer_MzML_indexedmzML], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_ISpectrumWriter_Write(objectPtr: Ptr[ThermoRawFileParser_Writer_ISpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_Metadata_new(): Ptr[ThermoRawFileParser_Writer_Metadata] = extern
  def ThermoRawFileParser_Writer_Metadata_addFileProperty(objectPtr: Ptr[ThermoRawFileParser_Writer_Metadata], value: Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = extern
  def ThermoRawFileParser_Writer_Metadata_addInstrumentProperty(objectPtr: Ptr[ThermoRawFileParser_Writer_Metadata], value: Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = extern
  def ThermoRawFileParser_Writer_Metadata_addScanSetting(objectPtr: Ptr[ThermoRawFileParser_Writer_Metadata], value: Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = extern
  def ThermoRawFileParser_Writer_Metadata_addMSData(objectPtr: Ptr[ThermoRawFileParser_Writer_Metadata], value: Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = extern
  def ThermoRawFileParser_Writer_Metadata_addSampleProperty(objectPtr: Ptr[ThermoRawFileParser_Writer_Metadata], value: Ptr[ThermoRawFileParser_Writer_CVTerm]): Unit = extern
  def ThermoRawFileParser_Writer_CVTerm_new(): Ptr[ThermoRawFileParser_Writer_CVTerm] = extern
  def ThermoRawFileParser_Writer_CVTerm_new_1(accession: CString, cvLabel: CString, name: CString, value: CString): Ptr[ThermoRawFileParser_Writer_CVTerm] = extern
  def ThermoRawFileParser_Writer_CVTerm_get_accession(objectPtr: Ptr[ThermoRawFileParser_Writer_CVTerm]): CString = extern
  def ThermoRawFileParser_Writer_CVTerm_get_cvLabel(objectPtr: Ptr[ThermoRawFileParser_Writer_CVTerm]): CString = extern
  def ThermoRawFileParser_Writer_CVTerm_get_name(objectPtr: Ptr[ThermoRawFileParser_Writer_CVTerm]): CString = extern
  def ThermoRawFileParser_Writer_CVTerm_get_value(objectPtr: Ptr[ThermoRawFileParser_Writer_CVTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_new(accession: CString, cvGroup: CString, name: CString, value: CString, valueAccession: CString): Ptr[ThermoRawFileParser_Writer_ProxiCvTerm] = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Accession(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Accession(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_CvGroup(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_CvGroup(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Name(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Name(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_Value(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_Value(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_get_ValueAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm]): CString = extern
  def ThermoRawFileParser_Writer_ProxiCvTerm_set_ValueAccession(objectPtr: Ptr[ThermoRawFileParser_Writer_ProxiCvTerm], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_MetadataWriter_new(outputDirectory: CString, metadataFileName: CString): Ptr[ThermoRawFileParser_Writer_MetadataWriter] = extern
  def ThermoRawFileParser_Writer_MgfSpectrumWriter_Write(objectPtr: Ptr[ThermoRawFileParser_Writer_MgfSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_SpectrumWriter_Write(objectPtr: Ptr[ThermoRawFileParser_Writer_SpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_new(rawFileWrapper: Ptr[ThermoRawFileParser_RawFileWrapper]): Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter] = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_getSpectrumWrapper(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): Ptr[ThermoRawFileParser_Writer_SpectrumWrapper] = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_GetInMemoryStreamAsString(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): CString = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_ResetWriter(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], callGC: CBool): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_Write(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_CreateXmlWriter(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_CreateXmlWriter_1(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], omitXmlDeclaration: CBool): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteHeader(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteSpectrumNoReturn(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], scanNumber: int32_t, index: int32_t, serializeBinaryData: CBool): Unit = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteSpectrum(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter], scanNumber: int32_t, index: int32_t, serializeBinaryData: CBool): Ptr[ThermoRawFileParser_Writer_SpectrumWrapper] = extern
  def ThermoRawFileParser_Writer_MzMlSpectrumWriter_WriteFooter(objectPtr: Ptr[ThermoRawFileParser_Writer_MzMlSpectrumWriter]): Unit = extern
  def ThermoRawFileParser_Writer_OntologyMapping_getInstrumentModel(instrumentName: CString): Ptr[ThermoRawFileParser_Writer_MzML_CVParamType] = extern
  def ThermoRawFileParser_Writer_ParquetSpectrumWriter_Write(objectPtr: Ptr[ThermoRawFileParser_Writer_ParquetSpectrumWriter], firstScanNumber: int32_t, lastScanNumber: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_PScan_new(): Ptr[ThermoRawFileParser_Writer_PScan] = extern
  def ThermoRawFileParser_Writer_PScan_get_FileId(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CString = extern
  def ThermoRawFileParser_Writer_PScan_set_FileId(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_FileName(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CString = extern
  def ThermoRawFileParser_Writer_PScan_set_FileName(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_BasePeakIntensity(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_BasePeakIntensity(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_BasePeakMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_BasePeakMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_HighMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_HighMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_LowMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_LowMass(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_PacketType(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = extern
  def ThermoRawFileParser_Writer_PScan_set_PacketType(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_RetentionTime(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_RetentionTime(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_ScanNumber(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = extern
  def ThermoRawFileParser_Writer_PScan_set_ScanNumber(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_ScanType(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CString = extern
  def ThermoRawFileParser_Writer_PScan_set_ScanType(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CString): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_TIC(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): CDouble = extern
  def ThermoRawFileParser_Writer_PScan_set_TIC(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: CDouble): Unit = extern
  def ThermoRawFileParser_Writer_PScan_get_MsOrder(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan]): int32_t = extern
  def ThermoRawFileParser_Writer_PScan_set_MsOrder(objectPtr: Ptr[ThermoRawFileParser_Writer_PScan], value: int32_t): Unit = extern
  def ThermoRawFileParser_MainClass_get_Version(): CString = extern
  def ThermoRawFileParser_MainClass_set_Version(value: CString): Unit = extern
  def ThermoRawFileParser_RawFileParserException_new(): Ptr[ThermoRawFileParser_RawFileParserException] = extern
  def ThermoRawFileParser_RawFileParserException_new_1(message: CString): Ptr[ThermoRawFileParser_RawFileParserException] = extern
  def ThermoRawFileParser_RawFileParser_Parse(parseInput: Ptr[ThermoRawFileParser_ParseInput]): Unit = extern
  def ThermoRawFileParser_RawFileParser_InitRawFile(parseInput: Ptr[ThermoRawFileParser_ParseInput]): Ptr[ThermoRawFileParser_RawFileWrapper] = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_new(): Ptr[ThermoRawFileParser_XIC_JSONInputUnit] = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasMzRange(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CBool = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasMz(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CBool = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_HasSequence(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CBool = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Sequence(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CString = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Sequence(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_ToleranceUnit(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CString = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_ToleranceUnit(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Charge(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): int32_t = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Charge(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: int32_t): Unit = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_get_Filter(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit]): CString = extern
  def ThermoRawFileParser_XIC_JSONInputUnit_set_Filter(objectPtr: Ptr[ThermoRawFileParser_XIC_JSONInputUnit], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_JSONParser_ParseJSON(jsonString: CString): Ptr[ThermoRawFileParser_XIC_XicData] = extern
  def ThermoRawFileParser_XIC_XicData_new(): Ptr[ThermoRawFileParser_XIC_XicData] = extern
  def ThermoRawFileParser_XIC_XicData_new_1(copy: Ptr[ThermoRawFileParser_XIC_XicData]): Ptr[ThermoRawFileParser_XIC_XicData] = extern
  def ThermoRawFileParser_XIC_XicData_get_OutputMeta(objectPtr: Ptr[ThermoRawFileParser_XIC_XicData]): Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = extern
  def ThermoRawFileParser_XIC_XicData_set_OutputMeta(objectPtr: Ptr[ThermoRawFileParser_XIC_XicData], value: Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): Unit = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_new(): Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_new_1(copy: Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): Ptr[ThermoRawFileParser_XIC_XicOutputMeta] = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_get_base64(objectPtr: Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): CBool = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_set_base64(objectPtr: Ptr[ThermoRawFileParser_XIC_XicOutputMeta], value: CBool): Unit = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_get_timeunit(objectPtr: Ptr[ThermoRawFileParser_XIC_XicOutputMeta]): CString = extern
  def ThermoRawFileParser_XIC_XicOutputMeta_set_timeunit(objectPtr: Ptr[ThermoRawFileParser_XIC_XicOutputMeta], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_XicExecutor_run(parameters: Ptr[ThermoRawFileParser_XIC_XicParameters]): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_new(): Ptr[ThermoRawFileParser_XIC_XicParameters] = extern
  def ThermoRawFileParser_XIC_XicParameters_new_1(copy: Ptr[ThermoRawFileParser_XIC_XicParameters]): Ptr[ThermoRawFileParser_XIC_XicParameters] = extern
  def ThermoRawFileParser_XIC_XicParameters_get_help(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CBool = extern
  def ThermoRawFileParser_XIC_XicParameters_set_help(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_jsonFilePath(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CString = extern
  def ThermoRawFileParser_XIC_XicParameters_set_jsonFilePath(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_outputDirectory(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CString = extern
  def ThermoRawFileParser_XIC_XicParameters_set_outputDirectory(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_printJsonExample(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CBool = extern
  def ThermoRawFileParser_XIC_XicParameters_set_printJsonExample(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_outputFileName(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CString = extern
  def ThermoRawFileParser_XIC_XicParameters_set_outputFileName(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_base64(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CBool = extern
  def ThermoRawFileParser_XIC_XicParameters_set_base64(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_XIC_XicParameters_get_stdout(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters]): CBool = extern
  def ThermoRawFileParser_XIC_XicParameters_set_stdout(objectPtr: Ptr[ThermoRawFileParser_XIC_XicParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_XIC_XicMeta_new(): Ptr[ThermoRawFileParser_XIC_XicMeta] = extern
  def ThermoRawFileParser_XIC_XicMeta_new_1(copy: Ptr[ThermoRawFileParser_XIC_XicMeta]): Ptr[ThermoRawFileParser_XIC_XicMeta] = extern
  def ThermoRawFileParser_XIC_XicMeta_get_Filter(objectPtr: Ptr[ThermoRawFileParser_XIC_XicMeta]): CString = extern
  def ThermoRawFileParser_XIC_XicMeta_set_Filter(objectPtr: Ptr[ThermoRawFileParser_XIC_XicMeta], value: CString): Unit = extern
  def ThermoRawFileParser_XIC_XicReader_new(): Ptr[ThermoRawFileParser_XIC_XicReader] = extern
  def ThermoRawFileParser_XIC_XicReader_ReadXic(rawFilePath: CString, base64: CBool, xicData: Ptr[ThermoRawFileParser_XIC_XicData]): Unit = extern
  def ThermoRawFileParser_XIC_XicUnit_new(): Ptr[ThermoRawFileParser_XIC_XicUnit] = extern
  def ThermoRawFileParser_XIC_XicUnit_new_1(copy: Ptr[ThermoRawFileParser_XIC_XicUnit]): Ptr[ThermoRawFileParser_XIC_XicUnit] = extern
  def ThermoRawFileParser_XIC_XicUnit_HasValidRanges(objectPtr: Ptr[ThermoRawFileParser_XIC_XicUnit]): CBool = extern
  def ThermoRawFileParser_XIC_XicUnit_get_Meta(objectPtr: Ptr[ThermoRawFileParser_XIC_XicUnit]): Ptr[ThermoRawFileParser_XIC_XicMeta] = extern
  def ThermoRawFileParser_XIC_XicUnit_set_Meta(objectPtr: Ptr[ThermoRawFileParser_XIC_XicUnit], value: Ptr[ThermoRawFileParser_XIC_XicMeta]): Unit = extern
  def ThermoRawFileParser_Util_PeptideData_get_Proton(): CDouble = extern
  def ThermoRawFileParser_Util_PeptideData_set_Proton(value: CDouble): Unit = extern
  def ThermoRawFileParser_Util_PeptideData_get_H2O(): CDouble = extern
  def ThermoRawFileParser_Util_PeptideData_set_H2O(value: CDouble): Unit = extern
  def ThermoRawFileParser_Util_Peptide_new(): Ptr[ThermoRawFileParser_Util_Peptide] = extern
  def ThermoRawFileParser_Util_Peptide_new_1(sequence: CString): Ptr[ThermoRawFileParser_Util_Peptide] = extern
  def ThermoRawFileParser_Util_Peptide_GetMz(objectPtr: Ptr[ThermoRawFileParser_Util_Peptide], z: int32_t): CDouble = extern
  def ThermoRawFileParser_Util_Peptide_get_Sequence(objectPtr: Ptr[ThermoRawFileParser_Util_Peptide]): CString = extern
  def ThermoRawFileParser_Query_ProxiSpectrum_new(): Ptr[ThermoRawFileParser_Query_ProxiSpectrum] = extern
  def ThermoRawFileParser_Query_ProxiSpectrum_AddAttribute(objectPtr: Ptr[ThermoRawFileParser_Query_ProxiSpectrum], accession: CString, cvGroup: CString, name: CString, value: CString, valueAccession: CString): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_new(): Ptr[ThermoRawFileParser_Query_QueryParameters] = extern
  def ThermoRawFileParser_Query_QueryParameters_new_1(copy: Ptr[ThermoRawFileParser_Query_QueryParameters]): Ptr[ThermoRawFileParser_Query_QueryParameters] = extern
  def ThermoRawFileParser_Query_QueryParameters_get_help(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CBool = extern
  def ThermoRawFileParser_Query_QueryParameters_set_help(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_get_rawFilePath(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CString = extern
  def ThermoRawFileParser_Query_QueryParameters_set_rawFilePath(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CString): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_get_scans(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CString = extern
  def ThermoRawFileParser_Query_QueryParameters_set_scans(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CString): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_get_outputFile(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CString = extern
  def ThermoRawFileParser_Query_QueryParameters_set_outputFile(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CString): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_get_noPeakPicking(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CBool = extern
  def ThermoRawFileParser_Query_QueryParameters_set_noPeakPicking(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_Query_QueryParameters_get_stdout(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters]): CBool = extern
  def ThermoRawFileParser_Query_QueryParameters_set_stdout(objectPtr: Ptr[ThermoRawFileParser_Query_QueryParameters], value: CBool): Unit = extern
  def ThermoRawFileParser_Query_QueryExecutor_new(): Ptr[ThermoRawFileParser_Query_QueryExecutor] = extern
  def ThermoRawFileParser_Query_QueryExecutor_Run(parameters: Ptr[ThermoRawFileParser_Query_QueryParameters]): Unit = extern
  def ThermoRawFileParser_Query_ProxiSpectrumReader_new(_queryParameters: Ptr[ThermoRawFileParser_Query_QueryParameters]): Ptr[ThermoRawFileParser_Query_ProxiSpectrumReader] = extern

  object implicits {
    
    implicit class struct__GArray_ops(val p: Ptr[struct__GArray]) extends AnyVal {
      def data: CString = p._1
      def data_=(value: CString): Unit = p._1 = value
      def len: gint = p._2
      def len_=(value: gint): Unit = p._2 = value
    }

    implicit class struct_MonoEmbedObject_ops(val p: Ptr[struct_MonoEmbedObject]) extends AnyVal {
      def _class: Ptr[MonoClass] = p._1
      def _class_=(value: Ptr[MonoClass]): Unit = p._1 = value
      def _handle: uint32_t = p._2
      def _handle_=(value: uint32_t): Unit = p._2 = value
    }

    implicit class struct_MonoEmbedArray_ops(val p: Ptr[struct_MonoEmbedArray]) extends AnyVal {
      def array: Ptr[GArray] = p._1
      def array_=(value: Ptr[GArray]): Unit = p._1 = value
    }
  }

  object struct__GArray {
    import implicits._
    def apply()(implicit z: Zone): Ptr[struct__GArray] = alloc[struct__GArray]
    def apply(data: CString, len: gint)(implicit z: Zone): Ptr[struct__GArray] = {
      val ptr = alloc[struct__GArray]
      ptr.data = data
      ptr.len = len
      ptr
    }
  }

  object struct_MonoEmbedObject {
    import implicits._
    def apply()(implicit z: Zone): Ptr[struct_MonoEmbedObject] = alloc[struct_MonoEmbedObject]
    def apply(_class: Ptr[MonoClass], _handle: uint32_t)(implicit z: Zone): Ptr[struct_MonoEmbedObject] = {
      val ptr = alloc[struct_MonoEmbedObject]
      ptr._class = _class
      ptr._handle = _handle
      ptr
    }
  }

  object struct_MonoEmbedArray {
    import implicits._
    def apply()(implicit z: Zone): Ptr[struct_MonoEmbedArray] = alloc[struct_MonoEmbedArray]
    def apply(array: Ptr[GArray])(implicit z: Zone): Ptr[struct_MonoEmbedArray] = {
      val ptr = alloc[struct_MonoEmbedArray]
      ptr.array = array
      ptr
    }
  }
}

